# Generated by Django 4.0.4 on 2022-06-06 09:26

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Laboratory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pharmacy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pharmacy_name', models.CharField(default='', max_length=200)),
                ('img', models.ImageField(blank=True, default='', null=True, upload_to='Phy_logo/')),
                ('email', models.EmailField(default='', max_length=254)),
                ('password', models.CharField(default='', max_length=100)),
                ('Callnumber', models.PositiveBigIntegerField(default=1)),
                ('Address', models.TextField(default='', max_length=300)),
                ('Note', models.TextField(default='', max_length=300)),
                ('forget_password_token', models.CharField(blank=True, max_length=100, null=True)),
                ('is_Active', models.BooleanField(default=True)),
                ('city', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Laboratory.labcity')),
            ],
        ),
        migrations.CreateModel(
            name='Add_New_Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, null=True, upload_to='Medicine_img')),
                ('Medicine_name', models.CharField(max_length=255)),
                ('Medicine_price', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('Medicine_Expiry_date', models.DateField()),
                ('Expiry_Alert_Date', models.DateField(default=datetime.date(2022, 6, 6))),
                ('Total_Stock', models.PositiveIntegerField(default=0)),
                ('Medicine_packaging', models.CharField(choices=[('Blister packs', 'Blister packs'), ('Bottles\\Sachets', 'Bottles\\Sachets')], default='Blister packs', max_length=200, null=True)),
                ('Description', models.TextField(blank=True, default='', null=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Delete', 'Delete'), ('Out of Stock', 'Out of Stock')], default='Active', max_length=200)),
                ('is_Expired', models.BooleanField(default=False)),
                ('Pharmacy', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Pharmacy_Store.pharmacy')),
            ],
        ),
    ]
