# Generated by Django 4.0.4 on 2022-07-05 21:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mainpage', '0001_initial'),
        ('Rider_dashboard', '0001_initial'),
        ('Laboratory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Add_New_Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, null=True, upload_to='Medicine_img')),
                ('Medicine_name', models.CharField(max_length=255)),
                ('Medicine_price', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('Medicine_Expiry_date', models.DateField()),
                ('Expiry_Alert_Date', models.DateField(default=django.utils.timezone.now)),
                ('Total_Stock', models.PositiveIntegerField(default=0)),
                ('Medicine_packaging', models.CharField(choices=[('Blister packs', 'Blister packs'), ('Bottles\\Sachets', 'Bottles\\Sachets')], default='Blister packs', max_length=200, null=True)),
                ('packing_cost', models.PositiveIntegerField(default=0)),
                ('Description', models.TextField(blank=True, default='', null=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Delete', 'Delete'), ('Out of Stock', 'Out of Stock')], default='Active', max_length=200)),
                ('is_Expired', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Pharmacy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pharmacy_name', models.CharField(default='', max_length=200)),
                ('img', models.ImageField(blank=True, default='', null=True, upload_to='Phy_logo/')),
                ('email', models.EmailField(default='', max_length=254)),
                ('password', models.CharField(default='', max_length=100)),
                ('Callnumber', models.PositiveBigIntegerField(default=1)),
                ('Address', models.TextField(default='', max_length=300)),
                ('Note', models.TextField(default='', max_length=300)),
                ('forget_password_token', models.CharField(blank=True, max_length=100, null=True)),
                ('is_Active', models.BooleanField(default=True)),
                ('city', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Laboratory.labcity')),
            ],
        ),
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Delivery_by', models.CharField(choices=[('Self', 'Self'), ('By_Rider', 'By_Rider')], default='Self', max_length=200, null=True)),
                ('Rider_Request_status', models.CharField(choices=[('Assign a Rider', 'Assign a Rider'), ('Pending', 'Pending'), ('Cancelled', 'Cancelled'), ('Completed', 'Completed')], default='Pending', max_length=50)),
                ('Rider_Request_Reject_Reason', models.CharField(default='Rider is not Available', max_length=200)),
                ('quantity', models.IntegerField()),
                ('price', models.IntegerField()),
                ('Total_price', models.IntegerField()),
                ('Address', models.CharField(blank=True, default='', max_length=300)),
                ('phone', models.BigIntegerField(blank=True, default='')),
                ('payment', models.CharField(choices=[('Unpaid', 'Unpaid'), ('Paid', 'Paid')], default='Unpaid', max_length=50)),
                ('order_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Conform', 'Conform'), ('Out for delivery', 'Out for delivery'), ('Rider Received Payment', 'Rider Received Payment'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled'), ('Dispatch', 'Dispatch')], default='Pending', max_length=200, null=True)),
                ('product_status', models.BooleanField(default=True)),
                ('is_Cancel', models.BooleanField(default=False)),
                ('Customer', models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='mainpage.patient')),
                ('Medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pharmacy_Store.add_new_medicine')),
                ('Pharmacy', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Pharmacy_Store.pharmacy')),
                ('Rider', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='Rider_dashboard.rider')),
            ],
        ),
        migrations.AddField(
            model_name='add_new_medicine',
            name='Pharmacy',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Pharmacy_Store.pharmacy'),
        ),
    ]
