# Generated by Django 4.0.4 on 2022-06-06 09:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Pharmacy_Store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_new_medicine',
            name='Expiry_Alert_Date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
