# Generated by Django 4.0.4 on 2022-07-05 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('CNIC', models.BigIntegerField(default=0)),
                ('Rider_city', models.CharField(max_length=100)),
                ('Callnumber', models.BigIntegerField(default=1)),
                ('img', models.ImageField(default='', upload_to='Rider_img/')),
                ('password', models.CharField(default='', max_length=100)),
                ('forget_password_token', models.CharField(max_length=100, null=True)),
                ('is_Active', models.BooleanField(default=True)),
                ('assign_task', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
