# Generated by Django 4.0.4 on 2022-06-06 09:26

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mainpage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Labname', models.CharField(default='', max_length=200)),
                ('img', models.ImageField(blank=True, default='', null=True, upload_to='lablogo/')),
                ('email', models.EmailField(default='', max_length=254)),
                ('password', models.CharField(default='', max_length=100)),
                ('Callnumber', models.PositiveIntegerField(default=1)),
                ('Address', models.TextField(default='', max_length=300)),
                ('Home_Sample', models.CharField(choices=[('Available', 'Available'), ('Not Available', 'Not Available')], default='Available', max_length=200, null=True)),
                ('forget_password_token', models.CharField(blank=True, max_length=100, null=True)),
                ('is_Active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Labcity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Lab_city_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Test_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Test_name', models.CharField(default='', max_length=200)),
                ('test_price', models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=5)),
                ('Home_Sample', models.BooleanField(blank=True, default=False)),
                ('laboratory', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Laboratory.lab')),
            ],
        ),
        migrations.CreateModel(
            name='Samplest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('Callnumber', models.BigIntegerField(default=1)),
                ('img', models.ImageField(default='', upload_to='Sample Collectors_img/')),
                ('CNIC', models.BigIntegerField(default=0)),
                ('password', models.CharField(default='', max_length=100)),
                ('forget_password_token', models.CharField(max_length=100, null=True)),
                ('is_Active', models.BooleanField(default=True)),
                ('assign_task', models.PositiveIntegerField(default=0)),
                ('Laboratory', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Laboratory.lab')),
            ],
        ),
        migrations.AddField(
            model_name='lab',
            name='city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Laboratory.labcity'),
        ),
        migrations.CreateModel(
            name='Book_Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Patient_Name', models.CharField(default='', max_length=100)),
                ('city', models.CharField(blank=True, default='', max_length=100)),
                ('Phone', models.BigIntegerField(blank=True, default=0)),
                ('Address', models.TextField(default='', max_length=300)),
                ('Test_date', models.DateField(default=datetime.date.today, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Conform', 'Conform'), ('Sample Collected', 'Sample Collected'), ('Test Report', 'Completed'), ('Cancelled', 'Cancelled'), ('Dispatch', 'Dispatch')], default='Pending', max_length=200, null=True)),
                ('payment', models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid')], default='Pending', max_length=50, null=True)),
                ('Test_Type', models.CharField(choices=[('home sample', 'home sample'), ('Lab Visit', 'Lab Visit')], default='Lab Visit', max_length=200, null=True)),
                ('Test_report', models.FileField(blank=True, default='', null=True, upload_to='Test Reports/')),
                ('year', models.CharField(blank=True, default=2022, max_length=100)),
                ('month', models.CharField(blank=True, default=6, max_length=100)),
                ('Book_Test', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Laboratory.test_list')),
                ('Laboratory', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Laboratory.lab')),
                ('Samplest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Laboratory.samplest')),
                ('email', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='mainpage.patient')),
            ],
        ),
    ]
