# Generated by Django 4.0.4 on 2022-07-01 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('Mn', models.IntegerField(default=0)),
                ('img', models.ImageField(blank=True, default='../static/deault_profile_image.png', upload_to='patient_img/')),
                ('email', models.EmailField(default='', max_length=254)),
                ('password', models.CharField(default='', max_length=100)),
                ('city', models.CharField(choices=[('Rawalpindi', 'Rawalpindi'), ('Islamabad', 'Islamabad'), ('Lahore', 'Lahore'), ('Karachi', 'Karachi'), ('Multan', 'Multan')], default='Select your city', max_length=200, null=True)),
                ('Address', models.TextField(blank=True, default='', max_length=300, null=True)),
                ('forget_password_token', models.CharField(blank=True, max_length=100, null=True)),
                ('is_Active', models.BooleanField(default=True)),
            ],
        ),
    ]
