# Generated by Django 4.0.4 on 2022-06-14 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patient',
            options={'managed': False},
        ),
    ]
