# Generated by Django 3.2.5 on 2022-02-13 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Systemadmin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='superadmin',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='lablogo/'),
        ),
    ]
