# Generated by Django 4.0.4 on 2022-06-06 09:31

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mainpage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Clinic_Name', models.CharField(default='', max_length=200)),
                ('Doctor_email', models.EmailField(blank=True, default='', max_length=200, null=True)),
                ('Location', models.CharField(max_length=200)),
                ('Doctor_Fee', models.PositiveIntegerField(blank=True, default=0)),
                ('Clinic_Number', models.PositiveIntegerField(default=1)),
                ('Patient_day', models.PositiveIntegerField(default=5)),
                ('Monday', models.BooleanField(default=True)),
                ('clinic_time_start', models.TimeField(blank=True, null=True)),
                ('clinic_time_end', models.TimeField(blank=True, null=True)),
                ('Tuesday', models.BooleanField(default=True)),
                ('Wednesday', models.BooleanField(default=True)),
                ('Thursday', models.BooleanField(default=True)),
                ('Friday', models.BooleanField(default=True)),
                ('Saturday', models.BooleanField(default=False)),
                ('Sunday', models.BooleanField(default=False)),
                ('is_Active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor_request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Doctor_name', models.CharField(default='', max_length=200)),
                ('email', models.EmailField(default='', max_length=254)),
                ('Gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=200, null=True)),
                ('Callnumber', models.BigIntegerField(default=1)),
                ('city', models.CharField(max_length=100)),
                ('Speciality', models.CharField(blank=True, max_length=200)),
                ('Doctor_PMID_number', models.BigIntegerField(default=0)),
                ('Status', models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Pending', max_length=20, null=True)),
                ('is_Accepted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Doctor_name', models.CharField(default='', max_length=200)),
                ('img', models.ImageField(blank=True, default='', null=True, upload_to='doctor_img/')),
                ('Gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=200, null=True)),
                ('Experience', models.PositiveIntegerField(blank=True, default=0)),
                ('email', models.EmailField(default='', max_length=254)),
                ('password', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('Callnumber', models.BigIntegerField(default=1)),
                ('city', models.CharField(max_length=100)),
                ('Speciality', models.CharField(max_length=200)),
                ('Doctor_PMID_number', models.BigIntegerField(default=0)),
                ('Address', models.TextField(blank=True, default='', max_length=300, null=True)),
                ('forget_password_token', models.CharField(blank=True, max_length=100, null=True)),
                ('is_Active', models.BooleanField(default=True)),
                ('is_Live', models.BooleanField(default=False)),
                ('Doctor_Clinic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Doctor.clinic')),
            ],
        ),
        migrations.CreateModel(
            name='Special',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Doctor_Speciality', models.CharField(max_length=100)),
                ('img', models.FileField(blank=True, null=True, upload_to='Doctors_Speciality_imgs/')),
                ('total_doctors', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Save_Medical_Reports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Reports', models.FileField(blank=True, default='', null=True, upload_to='Patient_save_Reports/')),
                ('Report_Title', models.CharField(max_length=200)),
                ('Doctor_name', models.CharField(max_length=200)),
                ('Patient_name', models.CharField(max_length=200)),
                ('Date', models.DateField(default=django.utils.timezone.now)),
                ('Report_time', models.TimeField(blank=True)),
                ('Note', models.TextField(blank=True)),
                ('Patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainpage.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Health_blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, default='', null=True, upload_to='Health_blogs_img/')),
                ('Health_blogs_issue', models.CharField(blank=True, max_length=200)),
                ('Main_heading', models.CharField(blank=True, max_length=200)),
                ('Health_blogs_Detail', models.TextField()),
                ('blog_create_time', models.DateTimeField(default=datetime.datetime(2022, 6, 6, 14, 31, 10, 158875))),
                ('Doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Doctor.doctors')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='', max_length=150)),
                ('patient_phone', models.PositiveBigIntegerField(default=0)),
                ('Gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=200, null=True)),
                ('Problem_detail', models.TextField(blank=True, null=True)),
                ('Appointment_date', models.DateField(blank=True, null=True)),
                ('Time_slot', models.TimeField(blank=True, null=True)),
                ('time_start', models.CharField(blank=True, max_length=100, null=True)),
                ('Status', models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Cancel', 'Cancel'), ('Completed', 'Completed'), ('Dispatch', 'Dispatch')], default='Pending', max_length=20)),
                ('appointment_cancel_reason', models.TextField(blank=True, default='', max_length=300, null=True)),
                ('Prescription', models.TextField(blank=True, default='', max_length=500, null=True)),
                ('Doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Doctor.doctors')),
                ('Medical_report_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Doctor.save_medical_reports')),
                ('Patients', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainpage.patient')),
            ],
        ),
    ]
