# Generated by Django 4.0.4 on 2022-08-09 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctors',
            name='Patient_satisfaction',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='doctors',
            name='Total_Reviews',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
