# Generated by Django 4.0.4 on 2022-06-06 09:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='health_blogs',
            name='blog_create_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 6, 14, 33, 1, 810658)),
        ),
    ]
