# Generated by Django 4.0.4 on 2022-08-09 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0002_doctors_patient_satisfaction_doctors_total_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctors',
            name='satisfaction_per',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
